branches:
  except:
    - gh-pages

install:
  - cinst drmemory

build_script:
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCARGO_DEBUG=4 ..
  - cmake --build .
  - ctest --output-on-failure
