branches:
  except:
    - gh-pages

install:
  - cinst drmemory.install -Version 1.8.0.8

build_script:
  - md build
  - cd build
  - cmake -DCARGO_DEBUG=4 ..
  - cmake --build . --config Debug
  - ctest --output-on-failure
