build_script:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\;%PATH%
  - SET PATH=c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\;%PATH%
  - vcvarsall.bat
  - cl /nologo /errorReport:prompt /DCARGO_TEST cargo.c
  - cargo.exe
